# Use postgres/example user/password credentials
version: '3.8'

services:
  postgress:
    container_name: desafio-impar
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: desafio-impar
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: desafio-impar-rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  rabbitmq-data:

