# Use postgres/example user/password credentials
version: '3.8'

services:
  postgress:
    container_name: desafio-impar
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: desafio-impar
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres